- name: Reload ssh config
  service:
    name: ssh
    state: reloaded
- name: Verify that Docker Engine is installed correctly
  command: docker run hello-world
  changed_when: False
- name: Verify that nginx is installed correctly
  command: nginx -v
  changed_when: False
- name: Reload nginx config
  service:
    name: nginx
    state: reloaded
