- name: Update package index and install packages
  apt:
    update_cache: yes
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
- name: Add Docker's official GPG key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Set up stable repository
  apt_repository:
    # Hack: docker-ce armhf build is not available for Ubuntu Focal Fossa
    repo: "deb [arch=armhf] https://download.docker.com/linux/ubuntu bionic stable"
- name: Install Docker Engine
  apt:
    state: latest
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  notify:
    - Verify that Docker Engine is installed correctly
- name: Create docker group
  group:
    name: docker
    state: present
- name: Add ubuntu user to the docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
- name: Install Docker SDK for Python
  apt:
    name: python3-docker
    state: latest
