- name: Create Pi-hole container
  community.general.docker_container:
    name: "{{ pihole_container_name }}"
    image: pihole/pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "{{ pihole_web_port }}:80"
    volumes:
      - /pihole/etc/pihole/:/etc/pihole/
      - /pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/
    env:
      TZ: Europe/Warsaw
      WEBPASSWORD: "{{ pi_hole_webpassword }}"
    capabilities:
      - NET_ADMIN
    restart_policy: unless-stopped
    pull: yes
    container_default_behavior: no_defaults
  notify:
    - Disable Pi-hole's query logging
