- name: Install ufw
  apt:
    name: ufw
    state: latest
    update_cache: yes
- name: Set default outgoing policy
  community.general.ufw:
    default: allow
    direction: outgoing
- name: Set default incoming policy
  community.general.ufw:
    default: deny
    direction: incoming
- name: Add rule allowing multicast traffic
  community.general.ufw:
    rule: allow
    from: '192.168.0.0/24'
    to: '224.0.0.0/24'
- name: Add rule allowing multicast traffic (IPv6)
  community.general.ufw:
    rule: allow
    from: 'fe80::/10'
    to: 'ff00::/8'
- name: Add ssh rule
  community.general.ufw:
    rule: allow
    app: OpenSSH
- name: Add rule allowing LLMNR traffic
  community.general.ufw:
    rule: allow
    port: '5355'
    from: '192.168.0.0/24'
- name: Enable ufw
  community.general.ufw:
    state: enabled
