- name: Install ufw
  apt:
    name: ufw
    state: latest
    update_cache: yes
- name: Set default outgoing policy
  community.general.ufw:
    default: allow
    direction: outgoing
- name: Set default incoming policy
  community.general.ufw:
    default: deny
    direction: incoming
- name: Add ssh rule
  community.general.ufw:
    rule: allow
    app: OpenSSH
- name: Add rule allowing private network traffic
  community.general.ufw:
    rule: allow
    from: '192.168.0.0/16'
- name: Add rule allowing link-local traffic
  community.general.ufw:
    rule: allow
    from: '169.254.0.0/16'
- name: Add rule allowing link-local traffic (IPv6)
  community.general.ufw:
    rule: allow
    from: 'fe80::/10'
- name: Enable ufw
  community.general.ufw:
    state: enabled
